#!/bin/sh
set -e

T=`mktemp`

IPV4=$(curl -s -4 ip.sb)

[ "$IPV4" = "" ] || IPV4="set_real_ip_from $IPV4;"

cat <<__EOF__>$T
# Cloud Flare
# Generated: `date`

# CF-IPSV4
`curl -sL https://www.cloudflare.com/ips-v4 | sed 's/^/set_real_ip_from /; s/$/;/'`

# LOCAL
set_real_ip_from 127.0.0.1;
$IPV4

real_ip_header    X-Forwarded-For;
real_ip_recursive on;
__EOF__

mv $T /etc/nginx/conf.d/realip.conf
chmod 644 /etc/nginx/conf.d/realip.conf
[ -f /run/nginx.pid ] && nginx -s reload

